on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    # Go
    #   # Log into Azure
    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDS_AUHOBBSGHE }}
    #     environment: ${{ secrets.AZURE_ENVIRONMENT }}

    #   # Deploy ARM template
    # - name: Run ARM deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ./azureDeploy.json
    #     parameters: >
    #       storageAccountType="Standard_LRS"
    #       location="USGovVirginia"

      # output containerName variable from template
    - name: Deploy ADF ARM templates
      shell: powershell
      env:
        TENANT_ID: "8a09f2d7-8415-4296-92b2-80bb4666c5fc"
        CLIENT_ID: "c58adfec-3e2e-4f52-a280-a82e2fbde1db"
        SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
        OBJECT_ID: "7e402f4f-1f4b-4f83-8aa1-cccee5d59232"
        SECRET: ${{ secrets.AZURE_SECRET }}
        ADF_SYNAPSE_CONN_CONNECTIONSTRING: ${{ secrets.ADF_SYNAPSE_CONN_CONNECTIONSTRING }}
        LS_ADLS_DI_001_ACCOUNTKEY: ${{ secrets.LS_ADLS_DI_001_ACCOUNTKEY }}
        LS_PDWALS_ACCOUNTKEY: ${{ secrets.LS_PDWALS_ACCOUNTKEY }}
        ls_Neo_EDP_connectionString: ${{ secrets.LS_NEO_EDP_CONNECTIONSTRING }}
        PDWDB1_PDWADLS_CONNECTIONSTRING: ${{ secrets.PDWDB1_PDWADLS_CONNECTIONSTRING }}
        PDWDB1_PDWADLS_PASSWORD: ${{ secrets.PDWDB1_PDWADLS_PASSWORD }}
        PDWDB1_PEXPLCSTG001_CONNECTIONSTRING: ${{ secrets.PDWDB1_PEXPLCSTG001_CONNECTIONSTRING }}
        PDWDB1_PEXPLCSTG001_PASSWORD: ${{ secrets.PDWDB1_PEXPLCSTG001_PASSWORD }}
        V1231DB1_INTEGRIFY_CONNECTIONSTRING: ${{ secrets.V1231DB1_INTEGRIFY_CONNECTIONSTRING }}
        PDWADLS_MI_LS_ACCOUNTKEY: ${{ secrets.PDWADLS_MI_LS_ACCOUNTKEY }}         

      run: |
        # Get-Module -ListAvailable Az* | format-table Name
        # Get-ChildItem ./
        Install-Module Az -AllowClobber -SkipPublisherCheck -Force
        $pw = ConvertTo-SecureString -String $env:SECRET -Force -AsPlainText
        $cred = New-Object System.Management.Automation.PSCredential($env:CLIENT_ID, $pw)
        $null = Connect-AzAccount -ServicePrincipal -Credential $cred -TenantId $env:TENANT_ID -Environment AzureUSGovernment
        $null = Select-AzSubscription -SubscriptionId $env:SUBSCRIPTION_ID
        # Get-AzResourceGroup | select *Name*

        function secure($title, $str) {
            # Write-Output (New-Object -TypeName PSObject -Property @{Name = $title})
            if (-not $str) {
              return ConvertTo-SecureString -AsPlainText -Force -String "NO PAYLOAD"
            }
            return ConvertTo-SecureString -AsPlainText -Force -String $str
        }

        $stored = "Hello I am stored"
        $o = New-Object -TypeName PSObject -Property @{StoredTitle = $stored}
        Write-Output $o

        Write-Output (New-Object -TypeName PSObject -Property @{Title = "ADF_Synapse_conn_connectionstringg"})
        $params = @{
          ADF_SYNAPSE_CONN_CONNECTIONSTRING = secure("ADF_SYNAPSE_CONN_STRING", $env:ADF_SYNAPSE_CONN_CONNECTIONSTRING)
        }
        Write-Output (New-Object -TypeName PSObject -Property @{Title = "ADF Synapse Connection String"; Payload = $params.ADF_SYNAPSE_CONN_CONNECTIONSTRING})


        $paramsObject = New-Object -TypeName PSObject -Property $params
        Write-Output $paramsObject

        $params = @{
          ResourceGroupName = "P-DWAnalytics-Dev"
          ADF_Synapse_Conn_connectionString = secure($env:ADF_SYNAPSE_CONN_CONNECTIONSTRING)
          LS_ADLS_DI_001_accountKey = secure($env:LS_ADLS_DI_001_ACCOUNTKEY)
          LS_PDWALS_accountKey = secure($env:LS_PDWALS_ACCOUNTKEY)
          ls_Neo_EDP_connectionString = secure($env:LS_NEO_EDP_CONNECTIONSTRING)
          pdwadls_mi_ls_accountKey = secure($env:PDWADLS_MI_LS_ACCOUNTKEY)
          pdwdb1_pdwadls_connectionString = secure($env:PDWDB1_PDWADLS_CONNECTIONSTRING)
          pdwdb1_pdwadls_password = secure($env:PDWDB1_PDWADLS_PASSWORD)
          pdwdb1_pexplcstg001_connectionString = secure($env:PDWDB1_PEXPLCSTG001_CONNECTIONSTRING)
          pdwdb1_pexplcstg001_password = secure($env:PDWDB1_PEXPLCSTG001_PASSWORD)
          vl231db1_integrify_connectionString = secure($env:V1231DB1_INTEGRIFY_CONNECTIONSTRING)
        }

        Write-Output $params


        New-AzResourceGroupDeployment -storageAccountType "Standard_LRS" -TemplateFile ./azureDeploy.json @params


        # New-AzResourceGroupDeployment -ResourceGroupName ghe -TemplateFile ./azureDeploy.json -storageAccountType "Standard_LRS" -this-is-a_TEST test-adf-adkjf_djf_FJ

